services:
  remote-multistreamer:
    image: ghcr.io/jlips24/fanout-live:latest
    container_name: remote-multistreamer
    restart: unless-stopped
    ports:
      - "1935:1935"
      - "8080:8080"
    volumes:
      - ./data:/config
